#!/usr/bin/env bash
# This script displays current directory content after first dash
for file in *
do
    if [[ "$file" == *-* ]]
    then
        echo "$file" | cut -d'-' -f2-
    else
        echo "$file"
    fi
done
